const menuButton=document.querySelector('.menu-button');const menu=document.querySelector('#menu');menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});document.querySelectorAll('#menu a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.open).scrollIntoView({behavior:'smooth'})));
const lifeData={adolescencia:{title:'Adolescencia',text:'Aprende sobre cambios de la pubertad, consentimiento, prevención de violencias, cuidado digital, preservativos, métodos anticonceptivos, ITS, VIH y servicios amigables.'},juventud:{title:'Juventud',text:'Cuida tu proyecto de vida mediante decisiones informadas, relaciones respetuosas, doble protección, pruebas y orientación oportuna.'},adultez:{title:'Adultez',text:'Mantén controles de salud, prevención de ITS, planificación reproductiva y atención frente a cambios, molestias o dificultades.'},gestacion:{title:'Gestación y posparto',text:'Inicia tempranamente el control prenatal, realiza las pruebas indicadas y solicita orientación anticonceptiva después del parto.'}};const lifeContent=document.querySelector('#life-content');function showLife(key){const item=lifeData[key];lifeContent.innerHTML=`<h3>${item.title}</h3><p>${item.text}</p>`}showLife('adolescencia');document.querySelectorAll('.life-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.life-tab').forEach(b=>b.classList.remove('active'));button.classList.add('active');showLife(button.dataset.life)}));
const filter=document.querySelector('#faq-filter');const faqItems=[...document.querySelectorAll('#faq-list details')];const empty=document.querySelector('#faq-empty');filter.addEventListener('input',()=>{const term=filter.value.trim().toLowerCase();let visible=0;faqItems.forEach(item=>{const match=item.textContent.toLowerCase().includes(term);item.hidden=!match;if(match)visible++});empty.hidden=visible!==0});
const toTop=document.querySelector('#to-top');window.addEventListener('scroll',()=>toTop.classList.toggle('visible',window.scrollY>700));toTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));

const progressBar=document.querySelector('#reading-progress-bar');
const updatePageState=()=>{const scrollable=document.documentElement.scrollHeight-window.innerHeight;const progress=scrollable>0?Math.min(100,(window.scrollY/scrollable)*100):0;progressBar.style.width=`${progress}%`;toTop.classList.toggle('visible',window.scrollY>700)};
window.addEventListener('scroll',updatePageState,{passive:true});updatePageState();

const revealItems=document.querySelectorAll('.content-section,.intro,.topic-card,.learning-module');
if('IntersectionObserver' in window){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -40px'});revealItems.forEach(item=>{item.classList.add('reveal');revealObserver.observe(item)})}else{revealItems.forEach(item=>item.classList.add('is-visible'))}

const navLinks=[...document.querySelectorAll('#menu a')];const trackedSections=navLinks.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);
if('IntersectionObserver' in window){const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-25% 0px -65%',threshold:0});trackedSections.forEach(section=>navObserver.observe(section))}
